[package]
name = "oxide-analyzer"
version = "0.1.0"
edition = "2021"

[dependencies]
oxide-compiler = { path = "../compiler" }
tokio = { version = "1.33.0", features = ["full"] }
tower-lsp = "0.20.0"
