[package]
name = "compiler"
version = "0.1.0"
edition = "2021"

[dependencies]
dashmap = "5.5.3"
lazy_static = "1.4.0"
notify = "6.1.1"
parking_lot = "0.12.1"
walkdir = "2"

[dependencies.salsa]
git = "https://github.com/salsa-rs/salsa"
package = "salsa-2022"
